global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'abc@gmail.com'
  smtp_auth_username: 'abc@gmail.com'
  smtp_auth_password: 'password'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-alert'

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'abc@gmail.com'
        from: 'abc@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'abc@gmail.com'
        auth_password: 'password'
        require_tls: true


